# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simcaledited.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

TEXTCOLOR = "color: #105652"



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWinow")
        MainWindow.resize(350, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OutputLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputLabel.setGeometry(QtCore.QRect(15, 15, 321, 125))
        self.centralwidget.setStyleSheet(TEXTCOLOR)
        
        
        #Output
        font = QtGui.QFont()
        font.setPointSize(36)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.OutputLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.OutputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OutputLabel.setObjectName("OutputLabel")
        

        #7
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('7'))
        self.sevenbutton.setGeometry(QtCore.QRect(25, 300, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setObjectName("sevenbutton")
        
        #8
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('8'))
        self.eightbutton.setGeometry(QtCore.QRect(100, 300, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        
        #divd
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('/'))
        self.divideButton.setGeometry(QtCore.QRect(250, 225, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        
        #9
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('9'))
        self.nineButton.setGeometry(QtCore.QRect(175, 300, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        
        #4
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('4'))
        self.fourButton.setGeometry(QtCore.QRect(25, 375, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        
        #5
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('5'))
        self.fiveButton.setGeometry(QtCore.QRect(100, 375, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        
        #mult
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('*'))
        self.multiplyButton.setGeometry(QtCore.QRect(250, 300, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(26)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        
        #6
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('6'))
        self.sixButton.setGeometry(QtCore.QRect(175, 375, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        
        #1
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('1'))
        self.oneButton.setGeometry(QtCore.QRect(25, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
       
       #2
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('2'))
        self.twoButton.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        
        #minus
        self.minusButton = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it('-'))
        self.minusButton.setGeometry(QtCore.QRect(250, 375, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        
        #3
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('3'))
        self.threeButton.setGeometry(QtCore.QRect(175, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        
        #0
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('0'))
        self.zeroButton.setGeometry(QtCore.QRect(25, 525, 150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        
        #plus
        self.plusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('+'))
        self.plusButton.setGeometry(QtCore.QRect(250, 450, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        
        #equal
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(250, 525, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        
        #decimal
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(175, 525, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        
        #remove
        self.cButtoon = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.delete_it())
        self.cButtoon.setGeometry(QtCore.QRect(175, 150, 150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.cButtoon.setFont(font)
        self.cButtoon.setObjectName("cButtoon")
        
        #Ce
        self.clearButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it('AC'))
        self.clearButton.setGeometry(QtCore.QRect(25, 150, 150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        
        #+/-
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(25, 225, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(24)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setObjectName("plusminusButton")

        
        

        #power
        self.powerButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.power_it())
        self.powerButton.setGeometry(QtCore.QRect(100, 225, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")

        #root
        self.rootButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.root_it())
        self.rootButton.setGeometry(QtCore.QRect(175, 225, 75, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        self.rootButton.setFont(font)
        self.rootButton.setObjectName("rootButton")



        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    
    def power_it(self):
        screen = self.OutputLabel.text()
        powered = str((f"{eval(screen)}**2"))
        if screen[0] == "-":
            self.OutputLabel.setText(powered[1::])
        else:
            self.OutputLabel.setText(powered)

    def root_it(self):
        screen = self.OutputLabel.text()
        squared = str((f"{eval(screen)}**0.5"))
        self.OutputLabel.setText(squared)
     

    #delete char
    def delete_it(self):
        #gathering what on the screen
        screen = self.OutputLabel.text()
        #remove last item
        screen = screen[:-1]
        #output
        self.OutputLabel.setText(screen)

    #decimal
    def dot_it(self):
        screen = self.OutputLabel.text()
        if screen[-1] == '.':
            pass 
        else:
            self.OutputLabel.setText(f'{screen}.')
    
    #equality
    def math_it(self):
        #gathering what on screen
        screen = self.OutputLabel.text()
        try:
            #calculate
            answer = eval(screen)
            #answer
            self.OutputLabel.setText(str(answer))
        except:
            #error
            self.OutputLabel.setText('ERROR')

    # +/-
    def plus_minus_it(self):
        #gathering what on screen
        screen = self.OutputLabel.text()
        if '-' in screen:
            self.OutputLabel.setText(screen.replace('-', ''))
        else:
            self.OutputLabel.setText(f'-{screen}')


    def press_it(self, pressed):
        if pressed == 'AC':
            self.OutputLabel.setText('0')
        #if start with 0 an delete 0
        else:
            if self.OutputLabel.text() == '0':
                self.OutputLabel.setText('')
            # concatenate
            self.OutputLabel.setText(f'{self.OutputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OutputLabel.setText(_translate("MainWindow", "0"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.divideButton.setText(_translate("MainWindow", "÷"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.multiplyButton.setText(_translate("MainWindow", "x"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.cButtoon.setText(_translate("MainWindow", "C"))
        self.clearButton.setText(_translate("MainWindow", "AC"))
        self.plusminusButton.setText(_translate("MainWindow", "±"))
        self.powerButton.setText(_translate("MainWindow", "x²"))
        self.rootButton.setText(_translate("MainWindow", "√x"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
